
Vagrant.configure("2") do |config|


  config.vm.define "vm_1" do |vm_1|
    vm_1.vm.synced_folder "/Users/andreirad/Workspace/", "/srv/workspace"
    #vm_1.vm.network "forwarded_port", guest: 80, host: 8086
    vm_1.vm.box = "ubuntu/bionic64"
    vm_1.vm.hostname = "vmlocaldev"
    vm_1.vm.network "private_network", ip: "10.30.0.101"
    vm_1.vm.boot_timeout = 600
    vm_1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
      vb.name = "vm_local_dev"
    end
  
    ####### Provision #######
    vm_1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provision/playbook.yml"
      ansible.verbose = true
    end

  end


end